{
    "openapi": "3.0.0",
    "info": {
        "title": "teste Verzel",
        "description": "Esta api tem o objetivo de demonstrar conhecimento em nodejs",
        "termsOfService": "A ser definido",
        "contact": {
            "email": "her_almeida23@hotmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333/api/v1",
            "description": "Api desenvolvimento"
        },
        {
            "url": "a ser definida",
            "description": "Api producao"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "summary": "Autenticar Usuario",
                "description": "Essa rota e a responsavel por autenticar e logar usuario",
                "tags": [
                    "usuario"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuario"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@hotmail.com",
                                        "password": "123456"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/UsuarioLogado"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "summary": "Cadastro Usuario",
                "description": "Essa rota e a responsavel por cadastrar novos usuarios",
                "tags": [
                    "usuario"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Usuario"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "nome": "testeUsuario",
                                        "email": "teste@hotmail.com",
                                        "password": "123456",
                                        "admin": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Este email ja esta cadastrado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuario"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Lista Usuarios",
                "description": "Essa rota e a responsavel por listar todos usuarios cadastrados",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Usuario"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "put": {
                "summary": "Atualiza cadastro Usuario",
                "description": "Essa rota e a responsavel por atualizar os dados do usuario",
                "tags": [
                    "usuario"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "description": "Id do usuario que ira atualizar os dados"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UsuarioUpdate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "email": "teste@hotmail.com",
                                        "oldPassword": "123456",
                                        "password": "1234567",
                                        "confirmPassword": "1234567"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Este email ja esta cadastrado"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "email": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/aulas": {
            "post": {
                "summary": "Cadastra Aulas",
                "description": "Essa rota e a responsavel por cadastrar novas aulas",
                "tags": [
                    "aula"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Aula"
                            },
                            "examples": {
                                "aula": {
                                    "value": {
                                        "id": 1010,
                                        "nome": "Nodejs",
                                        "descricao": "Nodejs um dos melhores frame",
                                        "modulo_id": 1,
                                        "data": "11/10/1994 10:30",
                                        "perfilUsuario": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Ja existe aula cadastrad com o codigo"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/AulaResponse"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Lista Aulas",
                "description": "Essa rota e a responsavel por listar todas as aulas cadastradas",
                "tags": [
                    "aula"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/AulaResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/aulas/{id}": {
            "put": {
                "summary": "Atualiza cadastro Aula",
                "description": "Essa rota e a responsavel por atualizar os dados da Aula",
                "tags": [
                    "aula"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id da aula que ira atualizar os dados"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AulaUpdate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "nome": "aula Update",
                                        "data": "11/10/1994 10:30",
                                        "perfilUsuario": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Ja existe aula cadastrad com o codigo"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/AulaResponse"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Busca aulas conforme modulo_id passado na requisição",
                "description": "Essa rota e a responsavel por listar os dados de uma aula especifico",
                "tags": [
                    "aula"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Modulo_id da aula que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/AulaResponse"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta aula unica",
                "description": "Essa rota e a responsavel por deletar aula conforme o id passado",
                "tags": [
                    "aula"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id da aula que ira ser deletada"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "object",
                                            "properties": {
                                                "mensagem": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/modulos": {
            "post": {
                "summary": "Cadastra Modulo",
                "description": "Essa rota e a responsavel por cadastrar Modulo",
                "tags": [
                    "modulo"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Modulo"
                            },
                            "examples": {
                                "modulo": {
                                    "value": {
                                        "nome": "Nodejs",
                                        "perfilUsuario": true
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Ja existe modulo cadastrad com o nome"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ModuloResponse"
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Lista Modulos",
                "description": "Essa rota e a responsavel por listar todos os modulos cadastrados",
                "tags": [
                    "modulo"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ModuloResponse"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/modulos/{id}": {
            "put": {
                "summary": "Atualiza cadastro Modulo",
                "description": "Essa rota e a responsavel por atualizar os dados da Aula",
                "tags": [
                    "modulo"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id do modulo que ira atualizar os dados"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/ModuloUpdate"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "nome": "modulo Update"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "403": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Error: Ja existe modulo cadastrad com o id"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Busca modulo conforme id passado na requisição",
                "description": "Essa rota e a responsavel por listar um modulo especifico",
                "tags": [
                    "modulo"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id do modulo que ira atualizar os dados"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/ModuloResponse"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Deleta modulo unico",
                "description": "Essa rota e a responsavel por deletar modulo conforme o id passado",
                "tags": [
                    "modulo"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "description": "Id do modulo que ira ser deletado"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "Error: Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/TokenInvalido"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "message": {
                                            "type": "object",
                                            "properties": {
                                                "mensagem": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Usuario": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "UsuarioUpdate": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "oldPassword": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "confirmPassword": {
                        "type": "string"
                    }
                }
            },
            "UsuarioLogado": {
                "type": "object",
                "properties": {
                    "user": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "email": {
                                "type": "string"
                            },
                            "admin": {
                                "type": "boolean"
                            }
                        }
                    },
                    "token": {
                        "type": "string"
                    }
                }
            },
            "Aula": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "modulo_id": {
                        "type": "integer"
                    },
                    "data": {
                        "type": "string"
                    }
                }
            },
            "AulaResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "nome": {
                        "type": "string"
                    },
                    "descricao": {
                        "type": "string"
                    },
                    "modulo": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "nome": {
                                "type": "string"
                            }
                        }
                    },
                    "data": {
                        "type": "string"
                    }
                }
            },
            "AulaUpdate": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "data": {
                        "type": "string"
                    },
                    "perfilUsuario": {
                        "type": "boolean"
                    }
                }
            },
            "Modulo": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "perfilUsuario": {
                        "type": "boolean"
                    }
                }
            },
            "ModuloResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer"
                    },
                    "nome": {
                        "type": "string"
                    }
                }
        },
        "ModuloUpdate": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                }
            }
        },
        "TokenInvalido": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "MensagemDelete": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "object",
                    "properties": {
                        "mensagem": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "securitySchemes": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
        }
    }
}
}